export const mockClasses = [
  {
    id: "1",
    title: "Morning Pilates Flow",
    type: "pilates",
    date: "2024-12-20",
    time: "08:00",
    duration: 60,
    instructor: "Emma Thompson",
    location: "Studio A",
    room: "Classroom 1",
    maxSpots: 12,
    bookedSpots: 8,
    price: 35,
    description:
      "A gentle flow to start your day with mindful movement and core strengthening.",
  },
  {
    id: "2",
    title: "HIIT Bootcamp",
    type: "hiit",
    date: "2024-12-20",
    time: "18:00",
    duration: 45,
    instructor: "Mike Rodriguez",
    location: "Studio B",
    room: "Classroom 2",
    maxSpots: 15,
    bookedSpots: 12,
    price: 30,
    description:
      "High-intensity interval training for maximum calorie burn and strength building.",
  },
];

export const mockBookings = [
  {
    id: "1",
    memberName: "Sarah Johnson",
    memberEmail: "sarah.j@email.com",
    className: "Morning Pilates Flow",
    date: "2024-12-20",
    time: "08:00",
    status: "confirmed",
    paymentStatus: "paid",
    bookingDate: "2024-12-18",
    price: 35,
  },
  {
    id: "2",
    memberName: "Mike Davis",
    memberEmail: "mike.d@email.com",
    className: "HIIT Bootcamp",
    date: "2024-12-20",
    time: "18:00",
    status: "confirmed",
    paymentStatus: "paid",
    bookingDate: "2024-12-19",
    price: 30,
  },
  {
    id: "3",
    memberName: "Emma Wilson",
    memberEmail: "emma.w@email.com",
    className: "Morning Pilates Flow",
    date: "2024-12-21",
    time: "08:00",
    status: "waitlist",
    paymentStatus: "pending",
    bookingDate: "2024-12-19",
    price: 35,
  },
  {
    id: "4",
    memberName: "John Smith",
    memberEmail: "john.s@email.com",
    className: "HIIT Bootcamp",
    date: "2024-12-19",
    time: "18:00",
    status: "cancelled",
    paymentStatus: "refunded",
    bookingDate: "2024-12-17",
    price: 30,
  },
];

export const mockMembers = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 123-4567",
    membershipType: "Premium",
    joinDate: "2024-01-15",
    status: "active",
    totalBookings: 24,
    lastVisit: "2024-12-18",
  },
  {
    id: "2",
    name: "Mike Davis",
    email: "mike.d@email.com",
    phone: "+1 (555) 234-5678",
    membershipType: "Basic",
    joinDate: "2024-03-22",
    status: "active",
    totalBookings: 12,
    lastVisit: "2024-12-19",
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma.w@email.com",
    phone: "+1 (555) 345-6789",
    membershipType: "Elite",
    joinDate: "2024-02-10",
    status: "active",
    totalBookings: 45,
    lastVisit: "2024-12-19",
  },
  {
    id: "4",
    name: "John Smith",
    email: "john.s@email.com",
    phone: "+1 (555) 456-7890",
    membershipType: "Premium",
    joinDate: "2024-06-05",
    status: "inactive",
    totalBookings: 8,
    lastVisit: "2024-11-15",
  },
];

export const INSTRUCTORS = ["Emma Thompson", "Sarah Lee", "John Carter"];

export const mockStats = {
  totalClasses: 156,
  totalBookings: 1247,
  revenue: 42350,
  activeMembers: 324,
};

export  const mockStudents = [
    {
      id: "1",
      classId: "1",
      name: "Sarah Johnson",
      email: "sarah.j@email.com",
      phone: "+1 (555) 123-4567",
      status: "Booked",
      bookingDate: "2024-12-18 10:30 AM",
    },
    {
      id: "2",
      classId: "1",
      name: "Mike Davis",
      email: "mike.d@email.com",
      phone: "+1 (555) 234-5678",
      status: "Booked",
      bookingDate: "2024-12-18 02:15 PM",
    },
    {
      id: "3",
      classId: "1",
      name: "Emma Wilson",
      email: "emma.w@email.com",
      phone: "+1 (555) 345-6789",
      status: "Waitlist",
      bookingDate: "2024-12-19 09:00 AM",
    },
    {
      id: "4",
      classId: "2",
      name: "John Smith",
      email: "john.s@email.com",
      phone: "+1 (555) 456-7890",
      status: "Booked",
      bookingDate: "2024-12-17 03:45 PM",
    },
    {
      id: "5",
      classId: "2",
      name: "Lisa Brown",
      email: "lisa.b@email.com",
      phone: "+1 (555) 567-8901",
      status: "Booked",
      bookingDate: "2024-12-18 11:20 AM",
    },
  ];
